
services:
  backend:
    image: kawambiit/esr-backend:latest
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:3000"
    env_file:
      - ./server/.env
  frontend:
    image: kawambiit/esr-frontend:latest
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
